# -*- coding: utf-8 -*-
"""Lab1_5216.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qdlwmG7GK0FydmRT9iu7xoUbHPkq3GnT

**Lab1**
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
fileData = pd.read_csv('/content/Pokemon.csv', index_col='Name', na_values=' ')

fileData.info()

fileData.head()

fileData.describe()

fileData.isna().sum()

factor= fileData[['HP','Attack','Defense','Speed']]

import seaborn as sns
sns.heatmap(factor.corr(), cmap = 'RdYlGn')